update PropTypes to import from 'PropTypes' instead of 'react'
shahen94/react-native-shape-image-view pull request #15
Opened 2018-05-20 00:55 UTC by h4m3d66

2018-05-20 08:15 UTC, shahen94 requested changes
You have wrong imports.

You need to install prop-types and then import it

2018-05-20 09:27 UTC, h4m3d66 commented
Sorry about that, I corrected it.

2018-05-20 10:40 UTC, shahen94 commented on lib/hexagonImage/hexagonImage.android.js
> +import PropTypes from 'PropTypes';
There's on package named `PropTypes`. Probably you mean  `prop-types` .

Please test your PR before opening it in Github

2018-09-06 19:28 UTC, shahen94 approved these changes

2018-09-06 19:28 UTC, merged